### ISSUE TITLE
Fails to build on Linux 2.6.31

### ISSUE THREAD

**Issue by crawfxrd** [datto/dattobd#61]
```
[root@segv-fc12 src]# make
if [ ! -f kernel-config.h ] || tail -1 kernel-config.h | grep -qv '#endif'; then ./genconfig.sh 2.6.31.5-127.fc12.x86_64; fi;
make -C /lib/modules/2.6.31.5-127.fc12.x86_64/build M=/root/dattobd/src modules
make[1]: Entering directory `/usr/src/kernels/2.6.31.5-127.fc12.x86_64'
  CC [M]  /root/dattobd/src/dattobd.o
/root/dattobd/src/dattobd.c:354: error: conflicting types for ‘blk_stack_limits’
include/linux/blkdev.h:920: note: previous declaration of ‘blk_stack_limits’ was here
/root/dattobd/src/dattobd.c: In function ‘blk_stack_limits’:
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:357: warning: type defaults to ‘int’ in declaration of ‘_min1’
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:357: warning: type defaults to ‘int’ in declaration of ‘_min2’
/root/dattobd/src/dattobd.c:357: error: ‘struct request_queue’ has no member named ‘max_sectors’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:358: warning: type defaults to ‘int’ in declaration of ‘_min1’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:358: warning: type defaults to ‘int’ in declaration of ‘_min2’
/root/dattobd/src/dattobd.c:358: error: ‘struct request_queue’ has no member named ‘max_hw_sectors’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:359: warning: type defaults to ‘int’ in declaration of ‘_min1’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:359: warning: type defaults to ‘int’ in declaration of ‘_min2’
/root/dattobd/src/dattobd.c:359: error: ‘struct request_queue’ has no member named ‘bounce_pfn’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:360: warning: type defaults to ‘int’ in declaration of ‘_min1’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:360: warning: type defaults to ‘int’ in declaration of ‘_min2’
/root/dattobd/src/dattobd.c:360: error: ‘struct request_queue’ has no member named ‘seg_boundary_mask’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:362: warning: type defaults to ‘int’ in declaration of ‘_min1’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:362: warning: type defaults to ‘int’ in declaration of ‘_min2’
/root/dattobd/src/dattobd.c:362: error: ‘struct request_queue’ has no member named ‘max_phys_segments’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:364: warning: type defaults to ‘int’ in declaration of ‘_min1’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:364: warning: type defaults to ‘int’ in declaration of ‘_min2’
/root/dattobd/src/dattobd.c:364: error: ‘struct request_queue’ has no member named ‘max_hw_segments’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
/root/dattobd/src/dattobd.c:366: warning: type defaults to ‘int’ in declaration of ‘_min1’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
/root/dattobd/src/dattobd.c:366: warning: type defaults to ‘int’ in declaration of ‘_min2’
/root/dattobd/src/dattobd.c:366: error: ‘struct request_queue’ has no member named ‘max_segment_size’
make[2]: *** [/root/dattobd/src/dattobd.o] Error 1
make[1]: *** [_module_/root/dattobd/src] Error 2
make[1]: Leaving directory `/usr/src/kernels/2.6.31.5-127.fc12.x86_64'
make: *** [default] Error 2
```
