### ISSUE TITLE
 dattobd-dkms  dattobd-utils E: Sub-process /usr/bin/dpkg returned an error code (1)

### ISSUE THREAD

**Issue by lxndrJ** [datto/dattobd#346]
Hello, can anyone help?

tried to install with `sudo apt-get install dattobd-dkms dattobd-utils` but somehow it is not working

This is the report /var/crash/dattobd-dkms.0.crash

ProblemType: Package
DKMSBuildLog:
 DKMS make.log for dattobd-0.11.2 for kernel 6.5.0-14-generic (x86_64)
 Fr 19. Jan 05:14:58 CET 2024
 make: Verzeichnis „/usr/src/linux-headers-6.5.0-14-generic“ wird betreten
 warning: the compiler differs from the one used to build the kernel
   The kernel was built by: x86_64-linux-gnu-gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
   You are using:           gcc-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
   CC [M]  /var/lib/dkms/dattobd/0.11.2/build/bio_helper.o
   CC [M]  /var/lib/dkms/dattobd/0.11.2/build/bio_list.o
   CC [M]  /var/lib/dkms/dattobd/0.11.2/build/bio_queue.o
   CC [M]  /var/lib/dkms/dattobd/0.11.2/build/blkdev.o
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c: In function ‘bio_list_empty’:
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:24:28: error: ‘NULL’ undeclared (first use in this function)
    24 |         return bl->head == NULL;
       |                            ^~~~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:10:1: note: ‘NULL’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
     9 | #include "bio_list.h"
   +++ |+#include <stddef.h>
    10 | 
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:24:28: note: each undeclared identifier is reported only once for each function it appears in
    24 |         return bl->head == NULL;
       |                            ^~~~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c: In function ‘bio_list_init’:
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:33:31: error: ‘NULL’ undeclared (first use in this function)
    33 |         bl->head = bl->tail = NULL;
       |                               ^~~~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:33:31: note: ‘NULL’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c: In function ‘bio_list_add’:
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:45:12: error: invalid use of undefined type ‘struct bio’
    45 |         bio->bi_next = NULL;
       |            ^~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:45:24: error: ‘NULL’ undeclared (first use in this function)
    45 |         bio->bi_next = NULL;
       |                        ^~~~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:45:24: note: ‘NULL’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:48:25: error: invalid use of undefined type ‘struct bio’
    48 |                 bl->tail->bi_next = bio;
       |                         ^~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c: In function ‘bio_list_pop’:
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:69:36: error: invalid use of undefined type ‘struct bio’
    69 |                 bl->head = bl->head->bi_next;
       |                                    ^~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:71:36: error: ‘NULL’ undeclared (first use in this function)
    71 |                         bl->tail = NULL;
       |                                    ^~~~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:71:36: note: ‘NULL’ is defined in header ‘<stddef.h>’; did you forget to ‘#include <stddef.h>’?
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:73:20: error: invalid use of undefined type ‘struct bio’
    73 |                 bio->bi_next = NULL;
       |                    ^~
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c: In function ‘bio_list_empty’:
 /var/lib/dkms/dattobd/0.11.2/build/bio_list.c:25:1: error: control reaches end of non-void function [-Werror=return-type]
    25 | }
       | ^
 cc1: some warnings being treated as errors
 make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/dattobd/0.11.2/build/bio_list.o] Fehler 1
 make[2]: *** Auf noch nicht beendete Prozesse wird gewartet …
 In file included from /var/lib/dkms/dattobd/0.11.2/build/bio_queue.h:10,
                  from /var/lib/dkms/dattobd/0.11.2/build/bio_queue.c:9:
 /var/lib/dkms/dattobd/0.11.2/build/includes.h:14:10: fatal error: linux/genhd.h: Datei oder Verzeichnis nicht gefunden
    14 | #include <linux/genhd.h>
       |          ^~~~~~~~~~~~~~~
 compilation terminated.
 make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/dattobd/0.11.2/build/bio_queue.o] Fehler 1
 In file included from /var/lib/dkms/dattobd/0.11.2/build/bio_helper.c:7:
 /var/lib/dkms/dattobd/0.11.2/build/includes.h:14:10: fatal error: linux/genhd.h: Datei oder Verzeichnis nicht gefunden
    14 | #include <linux/genhd.h>
       |          ^~~~~~~~~~~~~~~
 compilation terminated.
 make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/dattobd/0.11.2/build/bio_helper.o] Fehler 1
 In file included from /var/lib/dkms/dattobd/0.11.2/build/blkdev.h:10,
                  from /var/lib/dkms/dattobd/0.11.2/build/blkdev.c:7:
 /var/lib/dkms/dattobd/0.11.2/build/includes.h:14:10: fatal error: linux/genhd.h: Datei oder Verzeichnis nicht gefunden
    14 | #include <linux/genhd.h>
       |          ^~~~~~~~~~~~~~~
 compilation terminated.
 make[2]: *** [scripts/Makefile.build:251: /var/lib/dkms/dattobd/0.11.2/build/blkdev.o] Fehler 1
 make[1]: *** [/usr/src/linux-headers-6.5.0-14-generic/Makefile:2037: /var/lib/dkms/dattobd/0.11.2/build] Fehler 2
 make: *** [Makefile:234: __sub-make] Fehler 2
 make: Verzeichnis „/usr/src/linux-headers-6.5.0-14-generic“ wird verlassen
DKMSKernelVersion: 6.5.0-14-generic
Date: Fri Jan 19 05:15:00 2024
DuplicateSignature: dkms:dattobd-dkms:0.11.2-1.1ubuntu22.04:/var/lib/dkms/dattobd/0.11.2/build/bio_list.c:24:28: error: ‘NULL’ undeclared (first use in this function)
Package: dattobd-dkms 0.11.2-1.1ubuntu22.04
PackageVersion: 0.11.2-1.1ubuntu22.04
SourcePackage: dattobd-dkms
Title: dattobd-dkms 0.11.2-1.1ubuntu22.04: dattobd kernel module failed to build****

**Comment by Swistusmen** [comment]
Hi, we unfortunately don't have packages for kernel 6.5 yet :/ You can try to build it from source, but we are working on 6.5

**Comment by lxndrJ** [comment]
Okay thank you. Maybe I try when I have learned how to make containers

**Comment by Swistusmen** [comment]
Hi, depends what kind of containers will you pick- docker f.e. doesn't virtualize kernel. We should give support to this kernel soon

**Comment by lxndrJ** [comment]
Hi, do you know how I cant get rid of the package? 
its still in the apt tried `sudo apt purge dattobd-dkms` but there is an dpkg error 

E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by lxndrJ** [comment]
> Hi, do you know how I cant get rid of the package? its still in the apt tried `sudo apt purge dattobd-dkms` but there is an dpkg error
> 
> E: Sub-process /usr/bin/dpkg returned an error code (1)

:D it's always useful to write things down. I was searching and found the way how to remove the files manually. Now I don't get the error code while updating
