### ISSUE TITLE
Fails to build on Linux 2.6.35

### ISSUE THREAD

**Issue by crawfxrd** [datto/dattobd#59]
Attempting to build on Fedora Core 14 (2.6.35.14-106.fc14.x86_64).

```
[root@segv-fc14 dattobd]# make driver
make -C src
make[1]: Entering directory `/root/dattobd/src'
if [ ! -f kernel-config.h ] || tail -1 kernel-config.h | grep -qv '#endif'; then ./genconfig.sh 2.6.35.14-106.fc14.x86_64; fi;
make -C /lib/modules/2.6.35.14-106.fc14.x86_64/build M=/root/dattobd/src modules
make[2]: Entering directory `/usr/src/kernels/2.6.35.14-106.fc14.x86_64'
  CC [M]  /root/dattobd/src/dattobd.o
/root/dattobd/src/dattobd.c: In function ‘submit_bio_wait’:
/root/dattobd/src/dattobd.c:286:14: error: ‘BIO_RW_SYNC’ undeclared (first use in this function)
/root/dattobd/src/dattobd.c:286:14: note: each undeclared identifier is reported only once for each function it appears in
/root/dattobd/src/dattobd.c: In function ‘snap_handle_read_bio’:
/root/dattobd/src/dattobd.c:2369:46: error: ‘BIO_RW_SYNC’ undeclared (first use in this function)
make[3]: *** [/root/dattobd/src/dattobd.o] Error 1
make[2]: *** [_module_/root/dattobd/src] Error 2
make[2]: Leaving directory `/usr/src/kernels/2.6.35.14-106.fc14.x86_64'
make[1]: *** [default] Error 2
make[1]: Leaving directory 
```

**Comment by crawfxrd** [comment]
Fixed in ebc98aea8240b5bf938e7518a0e986b480948499.
