### ISSUE TITLE
cannot build in kernel linux 5.14.0-368.el9.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 21 18:07:33 UTC 2023

### ISSUE THREAD

**Issue by iv-dev** [datto/dattobd#335]
/home/r2b/Projects/dattobd-main/src/bio_helper.c: In function ‘dattobd_set_bio_ops’:

/home/r2b/Projects/dattobd-main/src/bio_helper.c:184:9: error: implicit declaration of function ‘bio_set_op_attrs’ [-Werror=implicit-function-declaration]

  184 |         bio_set_op_attrs(bio, op, op_flags);

      |         ^~~~~~~~~~~~~~~~

cc1: some warnings being treated as errors
**detailed log** 
**[makeLogErr.txt](https://github.com/datto/dattobd/files/13597591/makeLogErr.txt)**

**Comment by Swistusmen** [comment]
Hi, we officially do not support this OS yet, but I'll look at it, thank you for raising this issue

**Comment by iv-dev** [comment]
> Hi, we officially do not support this OS yet, but I'll look at it, thank you for raising this issue

Hi, thanks for your comment . But where can I find the list of supported versions of linux kernel and operating systems?

**Comment by Swistusmen** [comment]
Hi, so:
-we are currently supporting kernel till 5.15 mainline, Centos and RHEL have another versioning so their 5.14 isn't 5.14 we are supporting now. 
-list of operating systems: https://continuity.datto.com/help/Content/kb/siris-alto-nas/360040893811.html

**Comment by iv-dev** [comment]
> Hi, so: -we are currently supporting kernel till 5.15 mainline, Centos and RHEL have another versioning so their 5.14 isn't 5.14 we are supporting now. -list of operating systems: https://continuity.datto.com/help/Content/kb/siris-alto-nas/360040893811.html

Hi , thanks for your comment

**Comment by mihaime** [comment]
@Swistusmen are CentOS / RHEL on your radar for adding support in the nearby future?

**Comment by Swistusmen** [comment]
@iv-dev we have a pull request with fix for that, it needs to go through quality process, but pls expect fix soon
@mihaime yes they are, here we also have big improvements currently under testing
both of this PR when merge should give support for RHEL 9, Centos 9

**Comment by Swistusmen** [comment]
@iv-dev should work now

**Comment by iv-dev** [comment]
@Swistusmen 
Unfortunately, the build problem is still there
![изображение](https://github.com/datto/dattobd/assets/41507235/80592070-6551-4659-bc0e-558ec75971ed)

Full log
[Log.txt](https://github.com/datto/dattobd/files/13745611/Log.txt)

**Comment by Swistusmen** [comment]
Sorry for late response, was on holiday. Can you please provide the way how you are installing dattobd? I see in your logs:
grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied
performing sys_umount lookup
grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied
performing sys_oldumount lookup
grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied
performing sys_call_table lookup
grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied
performing printk lookup
grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied

and this worries me a lot.

**Comment by iv-dev** [comment]
> Sorry for late response, was on holiday. Can you please provide the way how you are installing dattobd? I see in your logs: grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied performing sys_umount lookup grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied performing sys_oldumount lookup grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied performing sys_call_table lookup grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied performing printk lookup grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied
> 
> and this worries me a lot.

Hello, I did not install dattobd, but built it from the source code according to the instructions given here.
https://github.com/datto/dattobd/blob/main/INSTALL.md

**Comment by iv-dev** [comment]
> Sorry for late response, was on holiday. Can you please provide the way how you are installing dattobd? I see in your logs: grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied performing sys_umount lookup grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied performing sys_oldumount lookup grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied performing sys_call_table lookup grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied performing printk lookup grep: /lib/modules/5.14.0-373.el9.x86_64/System.map: Permission denied
> 
> and this worries me a lot.

And yes, sorry for the oversight, I didn't run the mac with sudo privileges.
I restarted the project build with sudo privileges. The build errors are the same. The report is attached
[build_log.txt](https://github.com/datto/dattobd/files/13858000/build_log.txt)

**Comment by Swistusmen** [comment]
@iv-dev I am working on that issue just now, for sure problem reproduces and I am thankful for raising that. 
According to your latest message:

1) it's strange for me that you have in build_log: 
make[3]: Entering directory '/usr/src/kernels/5.14.0-373.el9.x86_64'
make[3]: Leaving directory '/usr/src/kernels/5.14.0-373.el9.x86_64'
Because it should be 
KDIR := /lib/modules/$(KERNELVERSION)/build from Makefile in src/.
Have you changed something here or it just happened? Does your code include any changes? 
[for  /lib/modules/$(KERNELVERSION)/build it still doesn't work, but issue is another]

2) Can you share commends you have used to install packages needed for building process?
3) Which commit are you building?

**Comment by iv-dev** [comment]
> @iv-dev I am working on that issue just now, for sure problem reproduces and I am thankful for raising that. According to your latest message:
> 
>     1. it's strange for me that you have in build_log:
>        make[3]: Entering directory '/usr/src/kernels/5.14.0-373.el9.x86_64'
>        make[3]: Leaving directory '/usr/src/kernels/5.14.0-373.el9.x86_64'
>        Because it should be
>        KDIR := /lib/modules/$(KERNELVERSION)/build from Makefile in src/.
>        Have you changed something here or it just happened? Does your code include any changes?
>        [for  /lib/modules/$(KERNELVERSION)/build it still doesn't work, but issue is another]
> 
>     2. Can you share commends you have used to install packages needed for building process?
> 
>     3. Which commit are you building?

Hi .I download and used the zip file of the main branch.
 I did not make any changes in the code

**Comment by Swistusmen** [comment]
Hi @iv-dev , unfortunately my current workload cannot let me fully focus on this ticket, although I've managed to do some work which results you should see here: https://github.com/Swistusmen/dattobd/tree/building-on-new-kernels I know it build on kernel pointed by you although I haven't done more than sudo make, so I wouldn't consider it as tested. At this level I need to jump to something else and will return to this within a month.

**Comment by iv-dev** [comment]
> Hi @iv-dev , unfortunately my current workload cannot let me fully focus on this ticket, although I've managed to do some work which results you should see here: https://github.com/Swistusmen/dattobd/tree/building-on-new-kernels I know it build on kernel pointed by you although I haven't done more than sudo make, so I wouldn't consider it as tested. At this level I need to jump to something else and will return to this within a month.

Hi. No problem, I understand the difficulty of the task and your workload:). Of course I'll wait.
 I can test my tasks on Ubuntu, no problem, but Сentos is more actual for my customers. Thank you.

**Comment by Swistusmen** [comment]
Of course I understand your needs and hope could dedicate to this task. Generally supporting Centos9 is hard cause it's releasing kernel non-stop- 5.14.0 is stable, but what goes further changes (you have made a ticket for 368, now you are building on 373, I have tested on 404 and it's not the newest).

**Comment by Swistusmen** [comment]
@mihaime I wanted to inform you that we officially released support for RHEL 9.3, so our latest tag works on it.
